--1 Create a numpy array with numpy.array module and with a data type integer and float.

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,10],dtype="int") 

In [5]:
print (a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
print(a.dtype)

int32


In [9]:
b=np.array([1,2,3,4,5,6,7,8,9,10],dtype="float")

In [11]:
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [13]:
print(b.dtype)

float64


In [ ]:
---2 Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.

In [15]:
zero_dim=np.array(50)

In [17]:
print(zero_dim)

50


In [19]:
print(zero_dim.shape)

()


In [21]:
print(zero_dim.ndim)

0


In [23]:
one_dim=np.array([1,2,3,4,5])

In [25]:
print(one_dim)

[1 2 3 4 5]


In [29]:
print(one_dim.shape)

(5,)


In [31]:
print(one_dim.ndim)

1


In [33]:
two_dim=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
print(two_dim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(two_dim.shape)

(3, 3)


In [39]:
print(two_dim.ndim)

2


In [41]:
three_dim=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [43]:
print(three_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [45]:
print(three_dim.shape)

(3, 2, 3)


In [47]:
print(three_dim.ndim)

3


In [51]:
four_dim=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [53]:
print(four_dim)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [57]:
print(four_dim.shape)

(1, 2, 2, 3)


In [59]:
print(four_dim.ndim)

4


In [ ]:
--3 Create a 2x2, 3x3, and 4x4 identity matrix using numpy

In [61]:
two_identity=np.identity(2)

In [63]:
print(two_identity)

[[1. 0.]
 [0. 1.]]


In [67]:
three_identity=np.identity(3)

In [69]:
print(three_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [71]:
four_identity=np.identity(4)

In [73]:
print(four_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
--4 Create a numpy array with shape 2x5 that has all the elements as zero.

In [75]:
c=np.zeros((2,5))

In [77]:
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [79]:
print(c.shape)

(2, 5)


In [81]:
d=np.eye(3)

In [83]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [85]:
e=np.fliplr(d)

In [87]:
print(e)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
--5 Create a numpy array that has the shape 3x5 and all the elements are 5.

In [89]:
f=np.full((3,5),5)

In [91]:
print(f)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [93]:
g=np.ones((3,5))

In [95]:
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [97]:
g=np.ones((3,5))*5

In [99]:
print(g)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
--6 Create a numpy array with random integers in the range 0-100, and the sample size should be 25.


In [101]:
w=np.random.randint(0,100,25)

In [103]:
print(w)

[16 34 23 97 76 80 58 19 25 97 51 88 11 28 76 41  6 48 60 65 77 22 41 10
 40]


In [105]:
print(w.shape)

(25,)


In [ ]:
--7 Create a numpy array with a shape 3x3 that has all elements as 1.

In [107]:
h=np.ones((3,3))

In [109]:
print(h)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [111]:
print(h.shape)

(3, 3)


In [ ]:
--8 Create a numpy array in the shape 2x3 with random integers in the range 0-100. 
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [113]:
mainarray=np.random.randint(0,100,size=(2,3))

In [115]:
print(mainarray)

[[87 23 98]
 [ 5 64 96]]


In [117]:
mainarray.resize(3,2)

In [119]:
mainarray

array([[87, 23],
       [98,  5],
       [64, 96]])

In [121]:
print(mainarray.shape)

(3, 2)


In [ ]:
--9 Create a random array, with the range 0-1000, with a size 50 and
step 2. Perform the following operations on the same.

a. Print the first ten elements of the array.

b. Print the last ten elements of the array

c. Print the elements from the indexes 10-25

d. Print the element at the index 22

e. Print the array using negative indexing.

f. Print the last ten elements of the array, using negative indexing

In [123]:
arr=np.random.randint(0,1000,size=50)

In [125]:
print(arr)

[630 688 494 562 604 771 614 744 103 908 404 193 141 310 587 953 490 494
  86 861 523 959 413 206 930 400  92 867 619 637 636 663 270 670 985 634
 746 843 959 339 948 817 188 525 507 766 831 981 383 271]


In [127]:
arr[:10]

array([630, 688, 494, 562, 604, 771, 614, 744, 103, 908])

In [129]:
arr[40:]

array([948, 817, 188, 525, 507, 766, 831, 981, 383, 271])

In [131]:
arr[10:26]

array([404, 193, 141, 310, 587, 953, 490, 494,  86, 861, 523, 959, 413,
       206, 930, 400])

In [133]:
arr[22]

413

In [135]:
arr[-10:]

array([948, 817, 188, 525, 507, 766, 831, 981, 383, 271])

In [ ]:
--10 Given a numpy array that has values = [1,2,3,4,5].
Perform the following operations.

a. Insert the element 6 at the end of the array.

b. Insert the element 10 at the beginning of the array.

c. Insert the element 30, before 4.

d. Update the element 5 as 50.

e. Delete the element 50 in the updated array.

f. Create a function to search for the element 30.

g. Sort the array in ascending order.

In [137]:
z=np.array([1,2,3,4,5])

In [139]:
z

array([1, 2, 3, 4, 5])

In [143]:
y=np.append(z,6)

In [145]:
y

array([1, 2, 3, 4, 5, 6])

In [147]:
x=np.insert(y,0,10)

In [149]:
x

array([10,  1,  2,  3,  4,  5,  6])

In [151]:
u=np.insert(x,4,30)

In [153]:
u

array([10,  1,  2,  3, 30,  4,  5,  6])

In [155]:
u[-2]=50

In [157]:
u

array([10,  1,  2,  3, 30,  4, 50,  6])

In [159]:
v=np.delete(u,6)

In [161]:
v

array([10,  1,  2,  3, 30,  4,  6])

In [163]:
w=np.where(v==30)

In [165]:
w

(array([4], dtype=int64),)

In [171]:
v.sort()

In [173]:
v

array([ 1,  2,  3,  4,  6, 10, 30])

In [175]:
k=np.sort(v)[::-1]

In [177]:
k

array([30, 10,  6,  4,  3,  2,  1])

In [179]:
k=np.where(k==30,3,k)

In [181]:
k

array([ 3, 10,  6,  4,  3,  2,  1])